---
title: "Curriculum Vitae"
---

## Downloads

<!-- {{< fa download >}} [CV](downloads/cv.txt)  -->

{{< fa download >}} [Resume](downloads/Resume - Hekman, Daniel.pdf) 

## Education

### Degrees 

 - University of Michigan - Ann Arbor: Bachelor's of Science
   - 2006 - 2010
   - Majors: Economics, Psychology
   - Minor: Statistics
 - University of Wisconsin - Madison: Master's of Science
   - 2019 - 2022
   - Department: Population Health Sciences
   - Concentration: Epidemiology
   - Thesis: An Evaluation of a Monte Carlo Simulation Approach to Selection Bias

### Certificates 

 - Certificate of Completion for Data Science Specialization
   - 2014
   - Issued by Johns Hopkins University [via Coursera](https://www.coursera.org/specializations/jhu-data-science)
 - Leadership in Population Health Improvement
   - 2016
   - University of Wisconsin (Online), Department of Population Health Sciences

## Work Experience
 - Data Scientist, Berbee-Walsh Department of Emergency Medicine (Madison, WI) | Sep 2019 - Present
   - University of Wisconsin School of Medicine and Public Health
   - Translating physician ideas into EHR phenotypes and quantifiable metrics
   - Working Dr. Brian Patterson to evaluate the effectiveness of a community falls prevention program
   - I work with operational leadership to monitor patient volumes and throughput, quantify outcomes of quality improvement initiatives, evaluate physician growth and opportunities for improvement with quantitative data, and generally run the numbers for all questions leadership has. 
 - SQL Database Administrator, Epic Hosting (Verona, WI) | Nov 2017 - Aug 2019
   - I worked as a database administrator for Epic’s hosted division, supporting dozens of servers across multiple customer clusters. 
   - I automated maintenance processes and best practice configurations with [Puppet](https://www.puppet.com/). 
 - Technical Services Engineer, Epic (Verona, WI) | Aug 2010 - Nov 2017
   - I was a technical services engineer (TS) for Epic’s Hospital Billing software, where I …
      - was a subject matter expert for all things revenue capture.
      - was a prolific coder.
      - was awarded “TS of the Year” after being nominated by my peers.
      - supported dozens of domestic go-lives and multiple international go-lives.


## Peer-Reviewed Publications

 - Barton, H. J., Maru, A., Leaf, M. A., __Hekman__, D. J., Wiegmann, D. A., Shah, M. N., & Patterson, B. W. (2024). Academic Detailing as a Health Information Technology Implementation Method: Supporting the Design and Implementation of an Emergency Department–Based Clinical Decision Support Tool to Prevent Future Falls. JMIR Human Factors, 11, e52592. https://doi.org/10.2196/52592
 - Barton, H. J., Maru, A., Lin, O., Leaf, M. A., __Hekman__, D. J., Wiegmann, D. A., Shah, M. N., & Patterson, B. W. (2024). Considerations for Developing Patient-centered Clinical Decision Support: Preventing Older Adult Falls after Emergency Department Visits. Proceedings of the Human Factors and Ergonomics Society Annual Meeting, 10711813241275504. https://doi.org/10.1177/10711813241275504
 - Brick, R., __Hekman__, D. J., Werner, N. E., Rodakowski, J., Cadmus-Bertram, L., & Fields, B. (2023). Health system and patient-level factors associated with multidisciplinary care and patient education among hospitalized, older cancer survivors. PEC Innovation, 3, 100192. https://doi.org/10.1016/j.pecinn.2023.100192
 - __Hekman__, D. J. B., Hanna J; Maru, Apoorva; Wills, Graham; Cochran, Amy L; Fritsch, Corey; Wiegmann, Douglas A. ;. Liao, Frank; Patterson, Brian W. (2024). Dashboarding to Monitor Machine Learning-based Clinical Decision Support Interventions. Applied Clinical Informatics, 00(AAM). https://doi.org/10.1055/a-2219-5175
 - __Hekman__, D. J., Cochran, A. L., Maru, A. P., Barton, H. J., Shah, M. N., Wiegmann, D., Smith, M. A., Liao, F., & Patterson, B. W. (2023). Effectiveness of an Emergency Department-Based Machine Learning Clinical Decision Support Tool to Prevent Outpatient Falls Among Older Adults: Protocol for a Quasi-Experimental Study. JMIR Research Protocols, 12, e48128. https://doi.org/10.2196/48128
 - __Hekman__, D. J., Rodakowski, J., Brick, R. S., Cadmus-Bertram, L., & Fields, B. (2021). Exploration of patient and caregiver cancer education using electronic health records. Journal of Geriatric Oncology. https://doi.org/10.1016/j.jgo.2021.06.008
 - Hoxha, I., __Hekman__, D. J., & Schnapp, B. (2024). Second- and third-year medical students’ clinical encounters in the emergency department. AEM Education and Training, 8(1), e10937. https://doi.org/10.1002/aet2.10937
 - Kern, M. W., Jewell, C. M., __Hekman__, D. J., & Schnapp, B. H. (2022). Number of Patient Encounters in Emergency Medicine Residency Does Not Correlate with In-Training Exam Domain Scores. The Western Journal of Emergency Medicine. https://doi.org/10.5811/westjem.2022.11.57997
 - Patterson, B. W., __Hekman__, D. J., Liao, F. J., Hamedani, A. G., Shah, M. N., & Afshar, M. (2024). Call me Dr Ishmael: Trends in electronic health record notes available at emergency department visits and admissions. JAMIA Open, 7(2), ooae039. https://doi.org/10.1093/jamiaopen/ooae039
 - Pulia, M. S., __Hekman__, D. J., Glazer, J. M., Barclay-Buchanan, C., Kuehnel, N., Ross, J., Sharp, B., Batt, R., & Patterson, B. W. (2020). Electronic Health Record-Based Surveillance for Community Transmitted COVID-19 in the Emergency Department. Western Journal of Emergency Medicine, 21(4), 748–751.
 - Tillman, D. S., Jewell, C. M., __Hekman__, D. J., Nicholson, A. M., Schnapp, B. H., Lasarev, M. R., Alexandridis, R., Hess, J. M., & Westergaard, M. C. (2022). Documentation from Trained Medical Students has Low Rate of Relative Downcoding for Emergency Medicine Encounters. AEM Education and Training, n/a(n/a), e10741. https://doi.org/10.1002/aet2.10741
 - Triche, B. L., Annamalai, A., Pooler, B. D., Glazer, J. M., Zadra, J. D., Barclay-Buchanan, C. J., __Hekman__, D. J., Mao, L., Pickhardt, P. J., & Lubner, M. G. (2022). Positive oral contrast material for CT evaluation of non-traumatic abdominal pain in the ED: prospective assessment of diagnostic confidence and throughput  metrics. Abdominal Radiology (New York), 47(8), 2956–2967. https://doi.org/10.1007/s00261-022-03574-6
 - Tsuchida, R. E., Doan, J., Losman, E. D., Haggins, A. N., Huang, R. D., __Hekman__, D. J., & Perry, M. A. (2023). Cultural Humility Curriculum to Address Healthcare Disparities for Emergency Medicine Residents. The Western Journal of Emergency Medicine, 24(2), 119–126. https://doi.org/10.5811/westjem.2023.1.58366
 - Tsuchida, R. E., Mbele, N., Chopra, Z., Moll, J., Burkhardt, J. C., __Hekman__, D. J., & Perry, M. A. (2024). Identifying the prevalence and characteristics of diversity, equity, and inclusion leaders in academic emergency medicine. AEM Education and Training, 8(2), e10965. https://doi.org/10.1002/aet2.10965

## Presentations, abstracts, and other scholarly output

 - Hekman, D. J. (2020, October 22). CA-CDS Reporting Dashboard at UW. 3rd Annual Child Abuse Clinical Decision Support Virtual Conference.
 - Hekman, D. J. (2021, January 25). On Balance: Costs and Benefits of School Shutdowns. On Balance. https://benefitcostanalysis.org/blog/on-balance/2021-01-25-on-balance-costs-and-benefits-of-school-shutdowns
 - Hekman, D., Maru, A. P., & Patterson, B. W. (2023, March 7). Dashboarding for Machine Learning-based Clinical Decision Support Implementation and Monitoring Toolkit [Text]. HIPxChange.Org. https://www.hipxchange.org/CDSDashboard
 - Hekman, D., Maru, Schnapp, B. (2024). Dashboard for Emergency Medicine Resident Learning Metrics Toolkit [Text]. HIPxChange.Org. https://www.hipxchange.org/EMResidentDashboard
 - Tsuchida, R. E. (2022). Cultural Humility Curriculum to Address Healthcare Disparities for Emergency Medicine Residents WACEP [Oral Presentation]. Society for Academic Emergency Medicine, New Orleans, LA.
 - Zurbuchen, R., Hekman, D., Tsuchida, R., Barclay-Buchanan, C., Darsie, M., Bernardoni, B., & Glazer, J. (2023). 264: AN EQUITY DASHBOARD OF POTENTIALLY LIFE-SAVING INTERVENTIONS REVEALS UNDER-TRIAGE OF FEMALE PATIENTS. Critical Care Medicine, 51, 117–117. https://doi.org/10.1097/01.ccm.0000906792.48840.b3
 - Many posters and abstracts I pulled data for that have been lost to the sands of time (and WACEP and SAEM archives)
 